repos:
  - repo: local
    hooks:
      - id: make-fix
        name: Run make fix (ruff linting and formatting)
        entry: make fix
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

  # Auto-update requirements.txt when pyproject.toml changes
  - repo: local
    hooks:
      - id: sync-requirements
        name: Sync requirements.txt from pyproject.toml
        entry: bash -c 'if git diff --cached --name-only | grep -q "pyproject.toml"; then uv export --no-hashes --no-dev -o requirements.txt && git add requirements.txt; fi'
        language: system
        pass_filenames: false
        stages: [pre-commit]
