site_name: Mange ta main
site_description: Recipe analytics and recommendation platform built with Streamlit.
site_url: https://regkhalil.github.io/mange-ta-main
repo_url: https://github.com/regkhalil/mange-ta-main
repo_name: regkhalil/mange-ta-main
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Application Features: app-features.md
  - Data Analytics: data-analytics.md
  - Preprocessing: preprocessing.md
  - CI/CD: cicd.md
  - Reference:
      - Services: reference/services.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_object_full_path: false
            show_source: false
            separate_signature: true
            merge_init_into_class: true
watch:
  - components
  - services
  - utils
  - preprocessing
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/regkhalil/mange-ta-main
